In [1]:
#Importing basic libraries and modules
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Defining sigmoid function
def sigmoid(z):
    s = 1/(1+np.exp(-z))    
    return s

In [3]:
# initialize parameters with zeros
def initialize_with_zeros(dim):
    w = np.zeros((dim,1))
    b = 0
    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    return w, b

In [4]:
# Forward and Back Propagate
def propagate(w, b, X, Y):
    m=X.shape[1]
    # FORWARD PROPAGATION
    A = sigmoid(np.dot(w.T,X)+b)
    # BACKWARD PROPAGATION
    dw = 1/m*(np.dot(X,(A-Y).T))
    db = 1/m*(np.sum(A-Y))
    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    grads = {"dw": dw,
             "db": db}
    return grads

In [5]:
# Optimizing Weights and Bias
def optimize(w, b, X, Y, num_iterations, learning_rate):
    for i in range(num_iterations):
        grads = propagate(w,b,X,Y)
        dw = grads["dw"]
        db = grads["db"]
        w = w-(learning_rate*dw)
        b = b-(learning_rate*db)
    params = {"w": w,
              "b": b}
    grads = {"dw": dw,
             "db": db}
    return params, grads

In [6]:
# Final Prediction
def predict(w, b, X):
    m=X.shape[1]
    Y_prediction = np.zeros((1,m))
    w = w.reshape(X.shape[0], 1)
    A = sigmoid(np.dot(w.T,X)+b)
    Y_prediction=np.where(A<=0.5,0.,1.)    
    assert(Y_prediction.shape == (1, m))
    return Y_prediction

In [7]:
# Logistic Regression 
def model(X, Y, num_iterations = 4000, learning_rate = 0.005):
        
    # initialize parameters with zeros
    w, b = initialize_with_zeros(X.shape[0])

    # Gradient descent
    parameters, grads = optimize(w, b, X, Y, num_iterations, learning_rate)
    
    # Retrieve parameters w and b from dictionary "parameters"
    w = parameters["w"]
    b = parameters["b"]
    
    # Predict test/train set examples 
    Y_prediction = predict(w, b, X)

    # Print train/test Errors
    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction - Y)) * 100))

    
    d = {"Y_prediction": Y_prediction,
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d

In [8]:
X=np.asarray([[0,0,1,1],[0,1,0,1]])
X.T

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

# **Implementing AND Gate**

In [9]:
Y_AND=np.asarray([0,0,0,1])
Y_AND

array([0, 0, 0, 1])

In [10]:
d_AND = model(X, Y_AND,num_iterations=3250)

train accuracy: 100.0 %


In [11]:
d_AND["Y_prediction"]

array([[0., 0., 0., 1.]])

In [12]:
d_AND["w"]

array([[0.84412047],
       [0.84412047]])

In [13]:
d_AND["b"]

-1.6860966924548797

# **Implementing OR Gate**

In [14]:
Y_OR=np.asarray([0,1,1,1])
Y_OR

array([0, 1, 1, 1])

In [15]:
d_OR = model(X,Y_OR,num_iterations=3900)

train accuracy: 100.0 %


In [16]:
d_OR["Y_prediction"]

array([[0., 1., 1., 1.]])

In [17]:
d_OR["w"]

array([[1.64826189],
       [1.64826189]])

In [18]:
d_OR["b"]

-0.006851432410889655

# **Implementing XOR Gate**

In [19]:
Y_XOR=np.asarray([0,1,1,0])
Y_XOR

array([0, 1, 1, 0])

In [20]:
d_XOR = model(X,Y_XOR,num_iterations=100000)

train accuracy: 50.0 %


In [21]:
d_XOR["Y_prediction"]

array([[0., 0., 0., 0.]])

In [22]:
d_XOR["w"]

array([[0.],
       [0.]])

In [23]:
d_XOR["b"]

0.0

# **Implementing NOT Gate**

In [24]:
X_NOT = np.asarray([[0,1]])
X_NOT

array([[0, 1]])

In [25]:
Y_NOT = np.asarray([1,0])
Y_NOT

array([1, 0])

In [26]:
d_NOT=model(X_NOT,Y_NOT,num_iterations=2)

train accuracy: 100.0 %


In [27]:
d_NOT["Y_prediction"]

array([[1., 0.]])

In [28]:
d_NOT["w"]

array([[-0.00249922]])

In [29]:
d_NOT["b"]

7.812498982748272e-07