In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd drive/MyDrive/Colab\ Notebooks/Machine\ Learning/Lab\ 6\ -\ Logistic\ Regression\ +\ SVM

/content/drive/MyDrive/Colab Notebooks/Machine Learning/Lab 6 - Logistic Regression + SVM


In [3]:
#importing modules and libraries
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import jaccard_similarity_score
%matplotlib inline 

In [4]:
#Reading data file
df = pd.read_csv("ChurnData.csv")
df['churn'] = df['churn'].astype('int')
df.head(10)

tenure   age  address  income   ed  ...  loglong  logtoll  lninc  custcat  churn
0    11.0  33.0      7.0   136.0  5.0  ...    1.482    3.033  4.913      4.0      1
1    33.0  33.0     12.0    33.0  2.0  ...    2.246    3.240  3.497      1.0      1
2    23.0  30.0      9.0    30.0  1.0  ...    1.841    3.240  3.401      3.0      0
3    38.0  35.0      5.0    76.0  2.0  ...    1.800    3.807  4.331      4.0      0
4     7.0  35.0     14.0    80.0  2.0  ...    1.960    3.091  4.382      3.0      0
5    68.0  52.0     17.0   120.0  1.0  ...    3.030    3.240  4.787      1.0      0
6    42.0  40.0      7.0    37.0  2.0  ...    2.110    3.157  3.611      4.0      0
7     9.0  21.0      1.0    17.0  2.0  ...    1.065    3.240  2.833      1.0      0
8    35.0  50.0     26.0   140.0  2.0  ...    1.872    3.314  4.942      3.0      0
9    49.0  51.0     27.0    63.0  4.0  ...    2.553    3.248  4.143      2.0      0

[10 rows x 28 columns]

In [5]:
#Setting dependent and Independent Variable
X = np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
y = np.asarray(df['churn'])
print(X)
print(y)

[[11. 33.  7. ...  5.  5.  0.]
 [33. 33. 12. ...  2.  0.  0.]
 [23. 30.  9. ...  1.  2.  0.]
 ...
 [ 6. 32. 10. ...  1. 10.  0.]
 [24. 30.  0. ...  4.  5.  0.]
 [61. 50. 16. ...  2. 22.  1.]]
[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 0 1 0 0 1 1 1 0 0 0 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0
 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]


In [6]:
#Data pre-performing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [7]:
#Performing Logisitic Regression using inbuilt function
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 7) (160,)
Test set: (40, 7) (40,)


In [8]:
#Perform logistic regression
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)

In [9]:
#Calculating probability value of LR
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.54132919, 0.45867081],
       [0.60593357, 0.39406643],
       [0.56277713, 0.43722287],
       [0.63432489, 0.36567511],
       [0.56431839, 0.43568161],
       [0.55386646, 0.44613354],
       [0.52237207, 0.47762793],
       [0.60514349, 0.39485651],
       [0.41069572, 0.58930428],
       [0.6333873 , 0.3666127 ],
       [0.58068791, 0.41931209],
       [0.62768628, 0.37231372],
       [0.47559883, 0.52440117],
       [0.4267593 , 0.5732407 ],
       [0.66172417, 0.33827583],
       [0.55092315, 0.44907685],
       [0.51749946, 0.48250054],
       [0.485743  , 0.514257  ],
       [0.49011451, 0.50988549],
       [0.52423349, 0.47576651],
       [0.61619519, 0.38380481],
       [0.52696302, 0.47303698],
       [0.63957168, 0.36042832],
       [0.52205164, 0.47794836],
       [0.50572852, 0.49427148],
       [0.70706202, 0.29293798],
       [0.55266286, 0.44733714],
       [0.52271594, 0.47728406],
       [0.51638863, 0.48361137],
       [0.71331391, 0.28668609],
       [0.

In [10]:
#Predicting Class 
yhat = LR.predict(X_test)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [11]:
#Calculating accuracy using jaccard accuracy
jaccard_similarity_score(y_test, yhat)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


0.75