In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd drive/MyDrive/Colab\ Notebooks/Machine\ Learning/Lab\ 5\ -\ Principal\ Component\ Analysis\ +\ Naive\ Bayes

/content/drive/MyDrive/Colab Notebooks/Machine Learning/Lab 5 - Principal Component Analysis + Naive Bayes


In [3]:
#Importing modules and libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [4]:
#Reading the dataframe
df=pd.read_csv("FuelConsumptionCo2_modified.csv")
df.head(10)

MODELYEAR  ENGINESIZE  ...  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
0       2014         2.0  ...                        33           196
1       2014         2.4  ...                        29           221
2       2014         1.5  ...                        48           136
3       2014         3.5  ...                        25           255
4       2014         3.5  ...                        27           244
5       2014         3.5  ...                        28           230
6       2014         3.5  ...                        28           232
7       2014         3.7  ...                        25           255
8       2014         3.7  ...                        24           267
9       2014         2.4  ...                        31           212

[10 rows x 8 columns]

In [5]:
#Setting Independent and Dependent Variable
X=df[['MODELYEAR','ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB','FUELCONSUMPTION_COMB_MPG']]
Y=df['CO2EMISSIONS']

In [6]:
lr = LinearRegression()
lr.fit(X,Y)
R=lr.score(X,Y)
R

0.8892861092642407

In [7]:
#Standardize data
X_std = StandardScaler().fit_transform(X)
X_std[:5]

array([[ 0.        , -0.9512918 , -0.99896853, -0.82855772, -0.99334135,
        -0.88430407,  0.87855306],
       [ 0.        , -0.66865251, -0.99896853, -0.5114328 , -0.63532912,
        -0.5685715 ,  0.34273362],
       [ 0.        , -1.30459092, -0.99896853, -1.77993246, -1.31555236,
        -1.63058106,  2.88787597],
       [ 0.        ,  0.10860554,  0.11424235, -0.14551944, -0.13411199,
        -0.13802708, -0.19308583],
       [ 0.        ,  0.10860554,  0.11424235, -0.29188478, -0.27731688,
        -0.28154188,  0.0748239 ]])

In [8]:
#Calculating Coovariance matrix
cov_matrix = np.cov(X_std,rowvar=False)
cov_matrix[:5]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.00093809,  0.93488671,  0.83300569,  0.77947632,
         0.82025088, -0.80931297],
       [ 0.        ,  0.93488671,  1.00093809,  0.79721981,  0.72527328,
         0.77751652, -0.77115244],
       [ 0.        ,  0.83300569,  0.79721981,  1.00093809,  0.96662415,
         0.9964763 , -0.93649032],
       [ 0.        ,  0.77947632,  0.72527328,  0.96662415,  1.00093809,
         0.98672862, -0.8946471 ]])

In [9]:
#Calculate Eigen decomposition
e_value, e_vector = np.linalg.eig(cov_matrix)

In [10]:
e_value[:5]

array([5.32701051, 0.47631511, 0.11436821, 0.06363999, 0.02425106])

In [11]:
e_vector[:5]

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00],
       [-3.95575339e-01, -5.24342622e-01, -8.98519326e-02,
         7.45584663e-01,  6.79345426e-02,  6.90880043e-05,
         0.00000000e+00],
       [-3.82028722e-01, -6.41750284e-01, -4.49962641e-02,
        -6.45431771e-01, -1.53635259e-01,  2.94043024e-05,
         0.00000000e+00],
       [-4.24891200e-01,  2.32190340e-01, -9.40016050e-02,
        -1.35791658e-01,  6.84550720e-01, -5.19297361e-01,
         0.00000000e+00],
       [-4.11674804e-01,  3.75827235e-01, -4.22323391e-01,
         5.43132285e-02, -6.50740544e-01, -2.90701766e-01,
         0.00000000e+00]])

In [12]:
#Percentage of knowledge in features
info_percent = (e_value/np.sum(e_value))*100
info_percent

array([8.87003000e+01, 7.93114515e+00, 1.90435040e+00, 1.05967239e+00,
       4.03805480e-01, 7.26563697e-04, 0.00000000e+00])

In [13]:
projected_1 = X_std.dot(e_vector.T[0])
projected_2 = X_std.dot(e_vector.T[1])

res = pd.DataFrame(projected_1, columns=['PC1'])
res['PC2'] = projected_2
res['Y'] = Y
res.head()

PC1       PC2    Y
0  2.253754  0.154000  196
1  1.506346  0.406282  221
2  4.070543 -0.598635  136
3  0.009696 -0.217195  255
4  0.301498 -0.397043  244

In [14]:
lr_ = LinearRegression()
X_ = res[['PC1','PC2']]
lr.fit(X_,Y)
R_=lr.score(X_,Y)
R_

0.8776342200686066